services:
  - type: web
    name: article-generator-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/index.js
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: OPENROUTER_REFERER
        value: https://your-app.com
      - key: OPENROUTER_TITLE
        value: Article Generator
